### ISSUE TITLE
Include minify javascript into release package

### ISSUE THREAD

**Issue by drikin** [twitter-archive/twitter-text-js#100]
I would like to have minify version of javascript in the release package.
I think it will be useful for other people.

**Comment by jakl** [comment]
Oh ok, we could put a minified file next to the full one.

**Comment by jakl** [comment]
Do you want to submit a pull request? Mention how to keep the minified file updated or make a rake task.

**Comment by drikin** [comment]
Hi @jakl,
Thank you for your quick reply. Sorry, I'm lazy I don't have any pull request so far. :crying_cat_face:

**Comment by drikin** [comment]
@jakl Honestly, I'm not good at Rake but I made the pull request. I will give you my pull request soon.

**Comment by drikin** [comment]
I made https://github.com/twitter/twitter-text-js/pull/102
So, I'd like to close this issue.
