### ISSUE TITLE
Library does not detect valid CCTLD's in extractUrl method

### ISSUE THREAD

**Issue by tommoor** [twitter-archive/twitter-text-js#20]
I am trying to use this library to build a prevalidator for tweets before they are sent to the twitter API however it does not pick up URL's such as bit.ly/12345 as being valid URLs. However, the twitter API does wrap these non-http cctld URLs, producing a longer tweet that is then rejected. 

I believe this bug is actually apparent on the twitter website and can be reproduced by filling the tweet box with upto 140 characters and including a bit.ly link without http. It will be impossible to send the tweet.

**Comment by keitaf** [comment]
Thank you for finding the issue. It's due to a bug introduced in 1.4.12, and I made a pull request to fix it.
https://github.com/twitter/twitter-text-js/pull/21
I'll merge it and deploy a new version with the fix asap.
