### ISSUE TITLE
Syntax error in javascript

### ISSUE THREAD

**Issue by braahyan** [twitter-archive/twitter-text-js#26]
Downloaded the twitter-text.js file and am getting a syntax error around the emoticon autolinking.

Uncaught SyntaxError: Invalid regular expression: /(8-#|8-E|+-(|`\@|`O|&lt;|:~(|}:o{|:-[|&gt;o&lt;|X-\/|[:-]-I-|\/\/\/\/Ö\\\\|(|:|\/)|?:*)|( | ))/: Nothing to repeat

its at line 159

**Comment by keitaf** [comment]
In what environment do you see the error? I cannot reproduce the error on Google Chrome and Firefox.

Also I believe this emoticon regex is not really used, so I am planning to remove it.

**Comment by braahyan** [comment]
gah, turns out the error was somehow from copy-pasting the source from github's raw view of the file. problem was solved by downloading the zip of the repo and then getting the file from there.

**Comment by killwing** [comment]
Similar issue when i load in Chrome Stable v15.0.874.121 m:
96: twttr.txt.regexen.atSigns = /[@＠]/;
144: twttr.txt.regexen.endHashtagMatch = /^(?:[#＃]|:\/\/)/;
I think it can't parse these special chars: ＠, ＃.
But in Chrome Dev it's fine. And i suggest use '\uFF20' etc. instead.

**Comment by keitaf** [comment]
@killwing Did you download the zip file or clone the repo? Or did you copy&paste the code from the web? I'm wondering if the file "twitter-text*.js" is correctly saved in UTF-8.

**Comment by killwing** [comment]
I just downloaded the zip file.
Also tested in IE9 v9.0.8112.16424IC (WIN7): SCRIPT1012: missing '/' twitter-text.js, line96
