### ISSUE TITLE
Some invalid tweets (dm commands) are reported as being valid

### ISSUE THREAD

**Issue by timhaines** [twitter-archive/twitter-text-js#77]
These are reported as being valid, but should be invalid:  'd', 'd ', 'm', 'm ', 'dm', 'dm ' 

There's probably other commands that I'm not aware of that should also be treated as invalid.

twttr.txt.isValidTweetText('d')

> true

**Comment by jakl** [comment]
SMS commands are listed here:
https://support.twitter.com/articles/14020-twitter-sms-commands

These commands aren't handled in twitter text. Errors should be returned by the SMS command handler.
