### ISSUE TITLE
.sx should be treated as a valid ccTLD

### ISSUE THREAD

**Issue by hepwori** [twitter-archive/twitter-text-js#90]
.sx domains have been available since mid-November 2012: http://www.register.eu/UK/news/reu-SX-domain-now-available-for-all.asp

Originally reported by a Twitter user here: http://twitter.com/KenCarpenter/status/310219988235612160

**Comment by jakl** [comment]
This is fixed by 161ec31, not sure when it will hit production but I'll find out.
