### ISSUE TITLE
Discard mentions, hashtags and urls

### ISSUE THREAD

**Issue by leog** [twitter-archive/twitter-text-js#97]
Hello.

Sorry to bother you, but I need to know if given a text I can get the same text without mentions, hashtags and urls.

Thanks a lot in advance.

**Comment by jakl** [comment]
Does this help?
http://requirebin.com/?gist=6048000

If not reopen. Happy to discuss.

**Comment by leog** [comment]
That helped a lot. Thanks jakl.

**Comment by jakl** [comment]
De nada
